from typing import Optional
from enum import Enum
import uuid
from pydantic import BaseModel, Field


class PlatformType(str, Enum):
    LINKEDIN = "linkedin"
    INSTAGRAM = "instagram"
    WHATSAPP = "whatsapp"
    TIKTOK = "tiktok"
    YOUTUBE_SHORTS = "youtube_shorts"
    X_TWITTER = "x_twitter"
    BLOG = "blog"
    NEWSLETTER = "newsletter"
    CUSTOM = "custom"


class PostStatus(str, Enum):
    DRAFT = "draft"
    PRODUCTION = "production"
    QA_APPROVED = "qa_approved"
    SCHEDULED = "scheduled"
    PUBLISHED = "published"
    ARCHIVED = "archived"


class CalendarEvent(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    client_id: str
    client_name: str
    concept_id: Optional[str] = None
    platform: PlatformType = PlatformType.LINKEDIN
    title: str = Field(description="Headline or title for the post")
    content: str = Field(description="Body copy, video script, or broadcast text")
    scheduled_date: str = Field(description="ISO date string, e.g. '2026-09-28'")
    scheduled_time: Optional[str] = Field(default="09:00", description="24-hr time string, e.g. '09:00'")
    status: PostStatus = PostStatus.SCHEDULED
    qa_score: Optional[int] = Field(default=None, description="QA Score out of 100 if generated by engine")
    source_formula: Optional[str] = Field(default=None, description="Viral psychological formula name")
    notes: Optional[str] = Field(default=None, description="Internal production or editorial notes")
    published_url: Optional[str] = Field(default=None, description="Live URL after publishing")
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


class CalendarEventCreate(BaseModel):
    client_id: str
    client_name: str
    concept_id: Optional[str] = None
    platform: PlatformType = PlatformType.LINKEDIN
    title: str
    content: str
    scheduled_date: str
    scheduled_time: Optional[str] = "09:00"
    status: Optional[PostStatus] = PostStatus.SCHEDULED
    qa_score: Optional[int] = None
    source_formula: Optional[str] = None
    notes: Optional[str] = None
    published_url: Optional[str] = None


class CalendarEventUpdate(BaseModel):
    title: Optional[str] = None
    content: Optional[str] = None
    platform: Optional[PlatformType] = None
    scheduled_date: Optional[str] = None
    scheduled_time: Optional[str] = None
    status: Optional[PostStatus] = None
    qa_score: Optional[int] = None
    source_formula: Optional[str] = None
    notes: Optional[str] = None
    published_url: Optional[str] = None


class CalendarEventReschedule(BaseModel):
    scheduled_date: str
    scheduled_time: Optional[str] = None


class CalendarEventStatusUpdate(BaseModel):
    status: PostStatus
